package cn.strongme.dao.advertisement;

import cn.strongme.dao.common.BaseMapper;
import cn.strongme.entity.advertisement.Ads;

public interface AdsDao extends BaseMapper<Ads>{

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
//    int insert(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
//    int insertSelective(Ads record);


    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
//    Ads selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
//    int updateByPrimaryKeySelective(Ads record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ads
     *
     * @mbg.generated
     */
//    int updateByPrimaryKey(Ads record);
}